version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:                                                 
        - DEV_DEPENDENCIES_FLAG:'--dev' # remove this if you don't want dev dependencies
    container_name: 'motion-detection'
    environment:
      - 'LOG_LEVEL=DEBUG'
    ports:
      - '5432:5432'
    volumes:
      - motion-detection-logs:/var/lib/logs
volumes:
  motion-detection-logs:
